/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlotsRouteImport } from './routes/plots'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as YieldRouteImport } from './routes/yield'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsRoute = PlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/costs': typeof CostsRoute
  '/diagnose': typeof DiagnoseRoute
  '/notifications': typeof NotificationsRoute
  '/plots': typeof PlotsRoute
  '/recommend': typeof RecommendRoute
  '/weather': typeof WeatherRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/costs': typeof CostsRoute
  '/diagnose': typeof DiagnoseRoute
  '/notifications': typeof NotificationsRoute
  '/plots': typeof PlotsRoute
  '/recommend': typeof RecommendRoute
  '/weather': typeof WeatherRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/costs': typeof CostsRoute
  '/diagnose': typeof DiagnoseRoute
  '/notifications': typeof NotificationsRoute
  '/plots': typeof PlotsRoute
  '/recommend': typeof RecommendRoute
  '/weather': typeof WeatherRoute
  '/yield': typeof YieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/costs'
    | '/diagnose'
    | '/notifications'
    | '/plots'
    | '/recommend'
    | '/weather'
    | '/yield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/costs'
    | '/diagnose'
    | '/notifications'
    | '/plots'
    | '/recommend'
    | '/weather'
    | '/yield'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/calendar'
    | '/community'
    | '/costs'
    | '/diagnose'
    | '/notifications'
    | '/plots'
    | '/recommend'
    | '/weather'
    | '/yield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  CostsRoute: typeof CostsRoute
  DiagnoseRoute: typeof DiagnoseRoute
  NotificationsRoute: typeof NotificationsRoute
  PlotsRoute: typeof PlotsRoute
  RecommendRoute: typeof RecommendRoute
  WeatherRoute: typeof WeatherRoute
  YieldRoute: typeof YieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots': {
      id: '/plots'
      path: '/plots'
      fullPath: '/plots'
      preLoaderRoute: typeof PlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  CostsRoute: CostsRoute,
  DiagnoseRoute: DiagnoseRoute,
  NotificationsRoute: NotificationsRoute,
  PlotsRoute: PlotsRoute,
  RecommendRoute: RecommendRoute,
  WeatherRoute: WeatherRoute,
  YieldRoute: YieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
